name: publish-nuget

on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
  push:
    branches: [ master ]

jobs:
  publish:
    name: build, test, pack & publish
    runs-on: ubuntu-latest
    environment: nuget-publish # Configured in Settings > Environments
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore

      # Publish
      - name: Publish DungAT.SqlBulkTools
        id: publish_main_nuget
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: SqlBulkTools/SqlBulkTools.csproj

          # Platform target to compile (default is empty/AnyCPU)
          # BUILD_PLATFORM: x64

          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: DungAT.SqlBulkTools

          # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
          # VERSION_FILE_PATH: Directory.Build.props

          # Regex pattern to extract version info in a capturing group
          VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$

          # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
          # VERSION_STATIC: 1.0.0

          # Flag to toggle git tagging, enabled by default
          # Do not push tags, we use tag to trigger nuget publish.
          TAG_COMMIT: false

          # Format of the git tag, [*] gets replaced with actual version
          # TAG_FORMAT: v*

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          # NUGET_SOURCE: https://api.nuget.org

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          INCLUDE_SYMBOLS: true

      - name: Publish DungAT.SqlBulkTools.EntityFramework6
        id: publish_ef6_nuget
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: SqlBulkTools.EntityFramework/SqlBulkTools.EntityFramework.csproj

          # Platform target to compile (default is empty/AnyCPU)
          # BUILD_PLATFORM: x64

          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: DungAT.SqlBulkTools.EntityFramework6

          # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
          # VERSION_FILE_PATH: Directory.Build.props

          # Regex pattern to extract version info in a capturing group
          VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$

          # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
          # VERSION_STATIC: 1.0.0

          # Flag to toggle git tagging, enabled by default
          # Do not push tags, we use tag to trigger nuget publish.
          TAG_COMMIT: false

          # Format of the git tag, [*] gets replaced with actual version
          # TAG_FORMAT: v*

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          # NUGET_SOURCE: https://api.nuget.org

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          INCLUDE_SYMBOLS: true

      - name: Publish DungAT.SqlBulkTools.EntityFrameworkCore
        id: publish_efcore_nuget
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: SqlBulkTools.EntityFrameworkCore/SqlBulkTools.EntityFrameworkCore.csproj

          # Platform target to compile (default is empty/AnyCPU)
          # BUILD_PLATFORM: x64

          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: DungAT.SqlBulkTools.EntityFrameworkCore

          # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
          # VERSION_FILE_PATH: Directory.Build.props

          # Regex pattern to extract version info in a capturing group
          VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$

          # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
          # VERSION_STATIC: 1.0.0

          # Flag to toggle git tagging, enabled by default
          # Do not push tags, we use tag to trigger nuget publish.
          TAG_COMMIT: false

          # Format of the git tag, [*] gets replaced with actual version
          # TAG_FORMAT: v*

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          # NUGET_SOURCE: https://api.nuget.org

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          INCLUDE_SYMBOLS: true
